### ISSUE TITLE
More than 3  areas of interest fails for sc_get_data

### ISSUE THREAD

**Issue by ryan-hill** [USEPA/StreamCatTools#14]
this_works <- sc_get_data(metric=metrics, aoi='catchment, watershed, riparian_catchment', comids)
also_works <- sc_get_data(metric=metrics, aoi='catchment, watershed, riparian_watershed', comids)
doesnt_work <- sc_get_data(metric=metrics, aoi='catchment, watershed, riparian_catchment, riparian_watershed', comids)

**Comment by mhweber** [comment]
This works correctly in current version of package - tested with:
              ``` library(StreamCatTools)
                  df <- sc_get_data(metric='PctUrbMd2006,DamDens,TRIDens', 
                  aoi='catchment, watershed, riparian_catchment, riparian_watershed', 
                  comid='179,1337,1337420')```
