### ISSUE TITLE
`sc_get_data` reversed args for showAreaSqKm, showPctFull

### ISSUE THREAD

**Issue by daauerbach** [USEPA/StreamCatTools#27]
Loving this package. I noticed today that the lines building the POST request have swapped the arguments for percent full and area. Easy workaround for me, and/but should be an easy fix in a next round of dev?

https://github.com/USEPA/StreamCatTools/blob/5800a43f13414f86ed4f7d3f912c24b0acfd54bc/R/sc_get_data.R#L79

**Comment by mahonmb** [comment]
Following up on this; I noticed there is also an issue in the same set of `post_body` code, where `count_only` is swapped for `conus`: `post_body <- paste0(post_body, "&countOnly=", conus)`.
