### ISSUE TITLE
Add functionality to return multiple full names

### ISSUE THREAD

**Issue by ryan-hill** [USEPA/StreamCatTools#41]
Should be able to return multiple full names of metrics if sc_fullname() code modified to:

`result <- resp[resp$dictionary.metric_prefix %in% unlist(strsplit(metric, split = ',')), 1]`

or 

`result <- data.frame(metric_name = resp[resp$dictionary.metric_prefix %in% unlist(strsplit(metric, split = ',')), 1])`

**Comment by mhweber** [comment]
Closed and resolved in #42
